<script>$(document).ready(function(){
  $('.parallax').parallax();
});
</script>
<div class="parallax-container">
  <div class="parallax"><img src="<?php echo $this->baseUrl('/visual/images/aluna1.jpg');?>"></div>
</div>
<div class="section white">
  <div class="row container">
    <h2 class="header red-text">Bem Vindo ao Dashboard</h2>
    <p class="grey-text text-darken-3 lighten-3">
      <p>Essa aplicação tem como objetivo um maior controle em seus compromissos escolares.</p>
    Aqui você poderá incluir eventos em um calendário pessoal e acompanhar seu rendimento escolar</p>
    <a class="btn red yellow-text" href="<?php echo $this->baseUrl('login');?>">Faça uma Conta Já!</a>
  </div>
</div>
<div class="parallax-container">
  <div class="parallax"><img src="<?php echo $this->baseUrl('/visual/images/1.jpg');?>"></div>
</div>
