<div class='container'>
	<div class='row'>
		<div class='col s12'>
			<div class='card-panel grey lighten-5 z-depth-3'>
				<div class='row valign-wrapper'>
					<div class='col s4'>
						<img src='<?php echo $this->baseUrl($_SESSION['avatar']) ?>' class="circle responsive-img"> <!-- notice the 'circle' class -->
					</div>
					<div class='col s10'>
						<span class='black-text'>
							<h5><?php echo $_SESSION['nome'] ?></h5>
							<p><a class='btn-floating btn-large waves-effect waves-light red' href='<?php echo $this->baseUrl('aluno/formulario/id_aluno/'. $_SESSION['id_aluno'])?>'><i class='material-icons'>mode_edit</i></a></p>
						</span>
					</div>
				</div>
			</div>
		</div>
		<div class='col s6'>
			<div class='card red darken-1 z-depth-3'>
				<div class='card-content white-text'>
					<span class='card-title'>Minhas Materias</span>
					<?php
					foreach($this->materias as $row){
					?>
					<p><i class="material-icons">get_app</i><a class="yellow-text" href=<?php echo $this->baseUrl('download/index/id_materia/' . $row['id_materia']);?>><?php echo $row['nome']?></a></p>
					<?php }?>
				</div>
				<div class='card-action'>
					<a class='yellow-text' href='<?php echo $this->baseUrl('materia/index') ?>'>Ver todos as Materias</a>
				</div>
			</div>
		</div>
		<div class='col s6'>
			<div class='card red darken-1 z-depth-3'>
				<div class='card-content green white-text'>
				<form action="<?php echo $this->baseUrl('home/diario')?>" method="post">
					<span class='card-title'>Diario</span>
					<div class="input-field">
						<input type="hidden" name="id_aluno" value="<?php echo $_SESSION['id_aluno'] ?>">
						<textarea id="icon_prefix2" name="texto" class="materialize-textarea"></textarea>
						<input type="submit" class="btn red" value="Enviar">
					</div>
					</form>
				</div>
			</div>
		</div>
		<div class='col s10'>
			<div class='card blue darken-1 z-depth-3' >
				<div class='card-content white-text'>
					<span class='card-title'>Próximos eventos</span>
					<table class="highlight">
						<thead>
							<tr>
								<th data-field="nome">Nome</th>
								<th data-field="data">Data</th>
							</tr>
						</thead>
						<tbody>
							<?php
									foreach($this->eventos as $row){
							?>
							<tr>
								
								
								<td><a class="yellow-text" href="<?php echo $this->baseUrl('calendario/formulario/id_evento/' . $row['id_evento']); ?>"><?php echo $row['nome']?></a></td>
								<td><?php echo $row['data']?></td>
							</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
				<div class='card-action'>
					<a class='white-text' href='<?php echo $this->baseUrl('calendario/index') ?>'>Ver meu calendario</a>
				</div>
				
			</div>
		</div>
	</div>
</div>