<div class="container">
	<div class="row">
		<div class="col s6">
			<div class="card red darken-1">
				<div class="card-content white-text">
					<span class="card-title">Minhas Materias</span>
					<p><a>Materia</a></p>
					<p><a>Materia</a></p>
					<p><a>Materia</a></p>
					<p><a>Materia</a></p>
				</div>
				<div class="card-action">
					<a class="yellow-text" href="<?php echo $this->baseUrl('materia/index') ?>">Ver todos as Materias</a>
				</div>
			</div>
		</div>
		<div class="col s6">
			<div class="card-panel grey lighten-5 z-depth-1">
          <div class="row valign-wrapper">
            <div class="col s4">
              <img src="http://www.codeproject.com/KB/GDI-plus/ImageProcessing2/img.jpg" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
            </div>
            <div class="col s10">
              <span class="black-text">
                <h5>meu nome</h5>
                <p>Lorem Ipsum</p>
                <p>Lorem Ipsum</p>
              </span>
            </div>
          </div>
        </div>
		</div>
		<div class="col s10">
			<div class="card blue darken-1">
				<div class="card-content white-text">
					<span class="card-title">Próximos eventos</span>
					<p>evento mais proximo</p>
					<p>evento antes desse</p>
				</div>
				<div class="card-action">
					<a class="white-text" href="<?php echo $this->baseUrl('calendario/index') ?>">Ver meu calendario</a>
				</div>
				
			</div>
		</div>
	</div>
</div>