<div class="container">
<div id="erroUser"></div>
<div id="erroEmail"></div>
	<h2>Aluno</h2>
	 <a class="btn red" href="<?php echo $this->baseUrl('aluno/excluir/id_aluno/' . $_SESSION['id_aluno']); ?>"><i class="material-icons">delete</i></a></td>
	<form action="<?php echo $this->baseUrl('aluno/gravar');?>" method="post">
		<input type="hidden" name="id_aluno" value="<?php echo $this->row['id_aluno']?>"/>
		<label>Nome : </label><input type="text" name="nome" value="<?php echo $this->row['nome']?>" required/>
		<label>Nasc : </label><input type="text" name="nasc" value="<?php echo $this->row['nasc']?>" required/>
		<label>Usuário : </label><input type="text" name="user" id="user" value="<?php echo $this->row['user']?>" required/>
		<label>Senha : </label><input type="password" name="pass" value="<?php echo $this->row['pass']?>" required/>
		<label>Email : </label><input type="text" name="email" id="email" value="<?php echo $this->row['email']?>" required/>
		<label>Avatar : </label><input type="text" name="avatar" value="<?php echo $this->row['avatar']?>"/>
		<br/>
		<br/>
		<input type="submit" class="btn btn-success" value="Enviar"/>
	</form>
</div>
<script type="text/javascript">
$(function(){
  $("#user").change(function verificarUser(){
    $('#erroUser').load('<?php echo $this->baseUrl('login/verificar/user/');?>' + $('#user').val());
    $('#resultado').html(data);
    });
    $("#email").change(function verificarEmail(){
      $('#erroEmail').load('<?php echo $this->baseUrl('login/verificar/email/');?>' + $('#email').val());
      $('#resultado').html(data);
    });
});
</script>