<div class="container">
	<h2>Materia</h2>
	<form action="<?php echo $this->baseUrl('materia/gravar');?>" method="post">
		<input type="text" name="id_aluno" value="<?php echo $this->dados['id_aluno']; ?>">
		<input type="hidden" name="id_materia" value="<?php echo $this->row['id_materia']?>"/>
		<label>Nome : </label><input type="text" name="nome" value="<?php echo $this->row['nome']?>" required/>
		<br/>
		<br/>
		<input type="submit" class="btn btn-success" value="Enviar"/>
	</form>
</div>