<div class="container">
<div class="row">
<div class="col s12">
    <a class="btn-floating red" href="<?php echo $this->baseUrl('calendario/formulario/id_aluno/'.$_SESSION['id_aluno']); ?>"><i class="material-icons">add</i></a>
    <h2>Listagem de Eventos</h2>
    <table>
        <thead>
            <tr>
            	<th data-field="acoes">Ações</th>
                <th data-field="nome">Nome</th>
                <th data-field="data">Data</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->dados as $row){ ?>
            <tr>      
            <td>
            	 <a href="<?php echo $this->baseUrl('calendario/formulario/id_evento/' . $row['id_evento']); ?>"><i class="material-icons red-text">mode_edit</i></a>
                <a href="<?php echo $this->baseUrl('calendario/excluir/id_evento/' . $row['id_evento']); ?>"><i class="material-icons red-text">delete</i></a>

            </td>
                <td><?php echo $row['nome']; ?></td>
                <td><?php echo $row['data']; ?></td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
</div>
</div>


